@startuml observer

class Policial {
    -string placa();
    -string name();
    -double km();

    +void estacionado();
    +void multado();
    +void update(String str);
}

class CarroSuspeito {
    -string placa();
    -string name();
    -double km();

    +void estacionado();
    +void multado();
    +void addObserver(Observer observer);
    +void notifyObservers();
}

interface Observer {
    
}

interface Carro{

}

interface Observable{

}

Policial --> CarroSuspeito

Policial --> Observer

Policial --> Carro

CarroSuspeito --> Carro

CarroSuspeito --> Observable

@enduml